apiVersion: v1
kind: Service
metadata:
  name: member-service
  namespace: dg0420-lifesub-ns
spec:
  selector:
    app: member
  ports:
  - port: 80
    targetPort: 8081
    protocol: TCP
  type: ClusterIP
