apiVersion: v1
kind: Service
metadata:
  name: mysub-service
  namespace: dg0420-lifesub-ns
spec:
  selector:
    app: mysub
  ports:
  - port: 80
    targetPort: 8082
    protocol: TCP
  type: ClusterIP
