apiVersion: v1
kind: Service
metadata:
  name: recommend-service
  namespace: dg0420-lifesub-ns
spec:
  selector:
    app: recommend
  ports:
  - port: 80
    targetPort: 8083
    protocol: TCP
  type: ClusterIP
