name: Backend CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: acrdigitalgarage03.azurecr.io
  SERVICES: member,mysub,recommend

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [member, mysub, recommend]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    
    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Build with Gradle
      run: |
        if [ "${{ matrix.service }}" = "mysub" ]; then
          ./gradlew :mysub-infra:clean :mysub-infra:build -x test
          echo "Built mysub-infra, checking output:"
          ls -la mysub-infra/build/libs/
        else
          ./gradlew :${{ matrix.service }}:clean :${{ matrix.service }}:build -x test
          echo "Built ${{ matrix.service }}, checking output:"
          ls -la ${{ matrix.service }}/build/libs/
        fi
    
    - name: Prepare JAR files with standard names
      run: |
        if [ "${{ matrix.service }}" = "mysub" ]; then
          cd mysub-infra/build/libs
          # Find the generated JAR and copy it to standard name
          GENERATED_JAR=$(ls *.jar | head -n 1)
          if [ -n "$GENERATED_JAR" ]; then
            echo "Found JAR: $GENERATED_JAR"
            cp "$GENERATED_JAR" mysub.jar
            echo "Copied to: mysub.jar"
            ls -la
          else
            echo "No JAR files found!"
            exit 1
          fi
        else
          cd ${{ matrix.service }}/build/libs
          # Find the generated JAR and copy it to standard name
          GENERATED_JAR=$(ls *.jar | head -n 1)
          if [ -n "$GENERATED_JAR" ]; then
            echo "Found JAR: $GENERATED_JAR"
            cp "$GENERATED_JAR" ${{ matrix.service }}.jar
            echo "Copied to: ${{ matrix.service }}.jar"
            ls -la
          else
            echo "No JAR files found!"
            exit 1
          fi
        fi
    
    - name: Run tests and generate coverage report
      run: |
        if [ "${{ matrix.service }}" = "mysub" ]; then
          ./gradlew :mysub-infra:test :mysub-infra:jacocoTestReport
        else
          ./gradlew :${{ matrix.service }}:test :${{ matrix.service }}:jacocoTestReport
        fi
    
    - name: SonarQube Scan
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      run: |
        if [ "${{ matrix.service }}" = "mysub" ]; then
          ./gradlew :mysub-infra:sonar \
            -Dsonar.projectKey=lifesub-${{ matrix.service }}-dg0420 \
            -Dsonar.projectName=lifesub-${{ matrix.service }}-dg0420 \
            -Dsonar.host.url="${{ secrets.SONAR_HOST_URL }}" \
            -Dsonar.login="${{ secrets.SONAR_TOKEN }}" \
            -Dsonar.java.binaries=build/classes/java/main \
            -Dsonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/test/jacocoTestReport.xml \
            -Dsonar.exclusions=**/config/**,**/entity/**,**/dto/**,**/*Application.class,**/exception/**
        else
          ./gradlew :${{ matrix.service }}:sonar \
            -Dsonar.projectKey=lifesub-${{ matrix.service }}-dg0420 \
            -Dsonar.projectName=lifesub-${{ matrix.service }}-dg0420 \
            -Dsonar.host.url="${{ secrets.SONAR_HOST_URL }}" \
            -Dsonar.login="${{ secrets.SONAR_TOKEN }}" \
            -Dsonar.java.binaries=build/classes/java/main \
            -Dsonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/test/jacocoTestReport.xml \
            -Dsonar.exclusions=**/config/**,**/entity/**,**/dto/**,**/*Application.class,**/exception/**
        fi
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.service }}-jar
        path: |
          ${{ matrix.service == 'mysub' && 'mysub-infra/build/libs/mysub.jar' || format('{0}/build/libs/{0}.jar', matrix.service) }}
        retention-days: 1

  release:
    needs: build
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ steps.generate-tag.outputs.image-tag }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Read deployment environment variables
      run: |
        while IFS='=' read -r key value; do
          # Skip comments and empty lines
          if [[ ! "$key" =~ ^#.*$ ]] && [[ -n "$key" ]] && [[ -n "$value" ]]; then
            echo "$key=$value" >> $GITHUB_ENV
          fi
        done < deployment/deploy_env_vars
    
    - name: Generate image tag
      id: generate-tag
      run: |
        IMAGE_TAG=$(date +'%Y%m%d%H%M%S')
        echo "image-tag=$IMAGE_TAG" >> $GITHUB_OUTPUT
        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
    
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        pattern: "*-jar"
        merge-multiple: false
    
    - name: Prepare build structure for Docker
      run: |
        echo "Setting up directory structure for Docker build..."
        
        # Create the expected directory structure
        mkdir -p member/build/libs
        mkdir -p mysub-infra/build/libs  
        mkdir -p recommend/build/libs
        
        # Copy JAR files from downloaded artifacts to expected locations
        if [ -f member-jar/member.jar ]; then
          cp member-jar/member.jar member/build/libs/member.jar
          echo "Copied member.jar"
        fi
        
        if [ -f mysub-jar/mysub.jar ]; then
          cp mysub-jar/mysub.jar mysub-infra/build/libs/mysub.jar
          echo "Copied mysub.jar"
        fi
        
        if [ -f recommend-jar/recommend.jar ]; then
          cp recommend-jar/recommend.jar recommend/build/libs/recommend.jar
          echo "Copied recommend.jar"
        fi
        
        echo "Verifying file structure:"
        echo "Member:"
        ls -la member/build/libs/ || echo "No member files"
        echo "Mysub:"
        ls -la mysub-infra/build/libs/ || echo "No mysub files"
        echo "Recommend:"
        ls -la recommend/build/libs/ || echo "No recommend files"
    
    - name: Login to Azure Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.registry }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
    
    - name: Build and push Docker images
      run: |
        for service in member mysub recommend; do
          if [ "$service" = "mysub" ]; then
            BUILD_LIB_DIR="mysub-infra/build/libs"
            JAR_FILE="mysub.jar"
          else
            BUILD_LIB_DIR="$service/build/libs"
            JAR_FILE="$service.jar"
          fi
          
          echo "Building image for $service..."
          echo "BUILD_LIB_DIR: $BUILD_LIB_DIR"
          echo "JAR_FILE: $JAR_FILE"
          echo "Full path: $BUILD_LIB_DIR/$JAR_FILE"
          
          # Verify JAR file exists before building
          if [ ! -f "$BUILD_LIB_DIR/$JAR_FILE" ]; then
            echo "ERROR: JAR file not found at $BUILD_LIB_DIR/$JAR_FILE"
            echo "Available files in $BUILD_LIB_DIR:"
            ls -la "$BUILD_LIB_DIR/" || echo "Directory does not exist"
            exit 1
          fi
          
          docker build \
            --build-arg BUILD_LIB_DIR="$BUILD_LIB_DIR" \
            --build-arg ARTIFACTORY_FILE="$JAR_FILE" \
            -f deployment/container/Dockerfile \
            -t ${{ env.registry }}/${{ env.image_org }}/$service:${{ env.IMAGE_TAG }} .
          
          echo "Pushing image for $service..."
          docker push ${{ env.registry }}/${{ env.image_org }}/$service:${{ env.IMAGE_TAG }}
        done

  deploy:
    needs: [build, release]
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Read deployment environment variables
      run: |
        while IFS='=' read -r key value; do
          # Skip comments and empty lines
          if [[ ! "$key" =~ ^#.*$ ]] && [[ -n "$key" ]] && [[ -n "$value" ]]; then
            echo "$key=$value" >> $GITHUB_ENV
          fi
        done < deployment/deploy_env_vars
    
    - name: Set image tag from release job
      run: |
        echo "IMAGE_TAG=${{ needs.release.outputs.image-tag }}" >> $GITHUB_ENV
    
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'
    
    - name: Get AKS credentials
      run: |
        az aks get-credentials --resource-group rg-digitalgarage-03 --name aks-digitalgarage-03 --overwrite-existing
    
    - name: Create namespace
      run: |
        kubectl create namespace ${{ env.namespace }} --dry-run=client -o yaml | kubectl apply -f -
    
    - name: Generate Kubernetes manifests
      run: |
        # Set image paths as environment variables
        export member_image_path="${{ env.registry }}/${{ env.image_org }}/member:${{ env.IMAGE_TAG }}"
        export mysub_image_path="${{ env.registry }}/${{ env.image_org }}/mysub:${{ env.IMAGE_TAG }}"
        export recommend_image_path="${{ env.registry }}/${{ env.image_org }}/recommend:${{ env.IMAGE_TAG }}"
        
        # Generate manifest from template
        envsubst < deployment/deploy.yaml.template > deployment/deploy.yaml
        
        echo "=== Generated Manifest ==="
        cat deployment/deploy.yaml
        echo "=========================="
    
    - name: Deploy to AKS
      run: |
        kubectl apply -f deployment/deploy.yaml
        
        echo "Waiting for deployments to be ready..."
        kubectl -n ${{ env.namespace }} wait --for=condition=available deployment/member --timeout=300s
        kubectl -n ${{ env.namespace }} wait --for=condition=available deployment/mysub --timeout=300s
        kubectl -n ${{ env.namespace }} wait --for=condition=available deployment/recommend --timeout=300s
        
        echo "=========================="
        echo "Backend Deployment Completed!"
        echo "Services:"
        kubectl -n ${{ env.namespace }} get svc
        echo "=========================="
